name: CI Build

on:
    # Run in master as CI
    push:
        branches:
        - master
    pull_request:
        branches:
        - master

jobs:
  xcode-build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Xcodebuild Action
      uses: sersoft-gmbh/xcodebuild-action@v2.0.1
      with:
        project: "Mlem.xcodeproj"
        target: "Mlem"
        sdk: "iphonesimulator16.4"
      