name: CI Build

on:
    # Run in master as CI
    push:
        branches:
        - master
    pull_request:
        branches:
        - master

jobs:
  xcode-build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: "Test SDK versions"
      run: |
        xcodebuild -showsdks
    - name: Xcodebuild Action
      uses: mxcl/xcodebuild@v1
      with:
        workspace: "Mlem.xcodeproj/project.xcworkspace"
        scheme: "Mlem"