name: CI Build

on:
    # Run in master as CI
    push:
        branches:
        - master
    pull_request:
        branches:
        - master

permissions: read-all|write-all

jobs:
  xcode-build:
    runs-on: macos-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: "Test SDK versions"
      run: |
        xcodebuild -showsdks
    - name: Xcodebuild Action
      run: |
        xcodebuild -project ./Mlem.xcodeproj -scheme "Mlem" -sdk "iphonesimulator16.2" -quiet -resultBundlePath "build_results.xcresult"
    - uses: kishikawakatsumi/xcresulttool@v1
      with:
        path: build_results.xcresult
      if: success() || failure()
      # ^ This is important because the action will be run
      # even if the test fails in the previous step.